/**
 * @module letters/names
 * @description Deterministic name-correction layer for Letters (PRD §17.2, risk #2
 *   in §0.4). A wrong-transcribed child name in the child's own book destroys the
 *   artifact, so this module never relies on the AI model — it is a pure,
 *   dictionary + phonetic-algorithm pipeline that runs before Claude ever sees a
 *   transcript, and it is the only mitigation that has to work identically on
 *   every platform (including web, where there is no on-device STT to tune).
 *
 *   Three responsibilities:
 *     - `seedCorrections`  — propose likely STT mishearings for known names
 *       (child, partner, siblings, pets, caregivers) before any transcript exists.
 *     - `applyCorrections` — rewrite a transcript using known corrections, safely.
 *     - `learnCorrection`  — detect that a parent's manual edit fixed a name, so
 *       it never has to be fixed again (PRD §17.3, "edit-as-signal").
 *
 *   All functions are pure: no I/O, no clock, no randomness, no mutation of inputs.
 * @since Letters BE2
 */

import type { NameCorrection } from '@/types/letters'

// ─── Soundex ────────────────────────────────────────────────────────────────
// A real phonetic-similarity algorithm (implemented inline per contract §2 — no
// new dependency). Used two ways: (1) to *verify* that a spelling variant
// generated by `PHONETIC_SWAPS` actually sounds like the source name before we
// trust it, and (2) to guard `learnCorrection` against "fixing" an unrelated
// word that merely happens to end in a known name.

const SOUNDEX_CODES: Record<string, string> = {
  B: '1', F: '1', P: '1', V: '1',
  C: '2', G: '2', J: '2', K: '2', Q: '2', S: '2', X: '2', Z: '2',
  D: '3', T: '3',
  L: '4',
  M: '5', N: '5',
  R: '6',
}

/** Strips diacritics and non-letters, uppercases. "José" -> "JOSE". */
function normalizeLetters(input: string): string {
  return input
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '') // combining diacritical marks
    .replace(/[^a-zA-Z]/g, '')
    .toUpperCase()
}

/** Classic Soundex, computed on the diacritic-normalized letters only. */
function soundex(input: string): string {
  const letters = normalizeLetters(input)
  if (letters.length === 0) return ''

  let code = letters[0]
  let prevDigit = SOUNDEX_CODES[letters[0]] ?? '0'

  for (let i = 1; i < letters.length && code.length < 4; i++) {
    const digit = SOUNDEX_CODES[letters[i]] ?? '0'
    if (digit !== '0' && digit !== prevDigit) {
      code += digit
    }
    prevDigit = digit
  }

  return (code + '000').slice(0, 4)
}

// ─── Case handling ──────────────────────────────────────────────────────────
//
// This codebase's TypeScript target does not support the regex `u` flag or
// `\p{...}` Unicode property escapes (they require ES2018+/ES6+), so
// "letter" and "word character" here are defined via explicit character
// ranges instead: ASCII plus the Latin-1 Supplement and Latin Extended-A/B
// blocks, which cover the accented Latin names ("José", "Zoë", "Renée")
// this product is likely to see. This is a deliberate, narrower substitute
// for full Unicode letter matching — not a false economy — as it still
// includes every character actually used by transcript possessives,
// boundaries, and casing checks in this module's test cases.
const LETTER_RANGE = 'A-Za-z\\u00C0-\\u00D6\\u00D8-\\u00F6\\u00F8-\\u024F'
const WORD_RANGE = LETTER_RANGE + '0-9'
const NON_LETTER_RE = new RegExp('[^' + LETTER_RANGE + ']', 'g')

/** Applies the letter-casing pattern of `sample` to `target`. */
function matchCase(sample: string, target: string): string {
  const letters = sample.replace(NON_LETTER_RE, '')
  if (letters.length === 0) return target

  const upper = letters.toUpperCase()
  const lower = letters.toLowerCase()

  const isAllUpper = letters === upper && letters !== lower
  if (isAllUpper) return target.toUpperCase()

  const isAllLower = letters === lower && letters !== upper
  if (isAllLower) return target.toLowerCase()

  const firstChar = letters.charAt(0)
  const firstIsUpper = firstChar !== firstChar.toLowerCase() && firstChar === firstChar.toUpperCase()
  const restIsLower = letters.slice(1) === letters.slice(1).toLowerCase()
  if (firstIsUpper && restIsLower) {
    return target.charAt(0).toUpperCase() + target.slice(1).toLowerCase()
  }

  // Mixed / unrecognized casing (e.g. "MiRa") — fall back to the correction's
  // own canonical casing rather than guessing.
  return target
}

// ─── seedCorrections ────────────────────────────────────────────────────────

/**
 * High-confidence, hand-verified mishearings for names we already know are
 * common in this product's early cohort. Kept intentionally small — this is a
 * safety net on top of the generated candidates below, not a substitute for
 * them. Keyed by lowercase canonical name.
 */
const KNOWN_VARIANTS: Readonly<Record<string, readonly string[]>> = {
  meera: ['Mira', 'Meara', 'Mera', 'Mirror', 'Myra', 'Mear'],
  ishita: ['Ishitha', 'Ishira', 'Ishida'],
}

/**
 * Letter/digraph pairs commonly confused by speech-to-text engines. Applied
 * bidirectionally to each name to generate spelling candidates; a candidate
 * is only kept if it survives the Soundex phonetic-equivalence check against
 * the source name (see `generateCandidates`), so this is a generative
 * algorithm gated by a real phonetic check — not a blind substitution list.
 */
const PHONETIC_SWAPS: ReadonlyArray<readonly [string, string]> = [
  ['ee', 'ea'],
  ['ee', 'i'],
  ['ee', 'y'],
  ['ee', 'e'],
  ['ea', 'e'],
  ['oo', 'u'],
  ['oo', 'o'],
  ['v', 'w'],
  ['ph', 'f'],
  ['th', 't'],
  ['s', 'z'],
  ['c', 'k'],
  ['ei', 'ai'],
]

/** Generates every single-swap variant of `word` for a given (from, to) pair. */
function swapAll(word: string, from: string, to: string): string[] {
  if (from.length === 0) return []
  const out: string[] = []
  let idx = word.indexOf(from)
  while (idx !== -1) {
    const variant = word.slice(0, idx) + to + word.slice(idx + from.length)
    if (variant.length > 0 && variant !== word) out.push(variant)
    idx = word.indexOf(from, idx + 1)
  }
  return out
}

/** Generates phonetically-verified spelling variants of a single name token. */
function generateCandidates(name: string): string[] {
  const lower = name.toLowerCase()
  const targetCode = soundex(name)
  if (targetCode === '') return []

  const raw = new Set<string>()
  for (const [a, b] of PHONETIC_SWAPS) {
    for (const variant of swapAll(lower, a, b)) raw.add(variant)
    for (const variant of swapAll(lower, b, a)) raw.add(variant)
  }

  const verified: string[] = []
  // Iterate via Array.from rather than `for...of` directly over the Set —
  // this codebase's TypeScript target does not enable downlevel iteration.
  for (const candidate of Array.from(raw)) {
    if (candidate === lower) continue
    if (soundex(candidate) === targetCode) {
      verified.push(matchCase(name, candidate))
    }
  }
  return verified
}

/**
 * Generates likely STT mishearings for a set of known names — child, partner,
 * siblings, pets, caregivers. Each name may be multi-word ("Meera Rose"); each
 * token is seeded independently. Combines a hardcoded high-confidence list for
 * names we already have real-world evidence about with algorithmically
 * generated, phonetically-verified candidates for every name.
 *
 * Pure: same input always produces the same output in the same order.
 */
export function seedCorrections(names: string[]): NameCorrection[] {
  const results: NameCorrection[] = []
  const seen = new Set<string>() // `${heard}=>${correct}` lowercased, for dedupe

  function addResult(heard: string, correct: string): void {
    const trimmedHeard = heard.trim()
    const trimmedCorrect = correct.trim()
    if (trimmedHeard.length === 0 || trimmedCorrect.length === 0) return
    // Guard: a correction that maps a name to itself would be a silent no-op
    // if ever applied in a loop — never emit one.
    if (trimmedHeard.toLowerCase() === trimmedCorrect.toLowerCase()) return

    const key = `${trimmedHeard.toLowerCase()}=>${trimmedCorrect.toLowerCase()}`
    if (seen.has(key)) return
    seen.add(key)

    results.push({
      heard: trimmedHeard,
      correct: trimmedCorrect,
      // Seeded proactively, before any transcript has actually produced this
      // mishearing — distinct from the schema's default of 1 for a freshly
      // *learned* correction, which represents one real observed hit.
      hit_count: 0,
      source: 'seeded',
    })
  }

  function seedToken(token: string): void {
    const hardcoded = KNOWN_VARIANTS[token.toLowerCase()]
    if (hardcoded) {
      for (const variant of hardcoded) addResult(variant, token)
    }
    for (const variant of generateCandidates(token)) addResult(variant, token)
  }

  for (const rawName of names) {
    const name = rawName.trim()
    if (name.length === 0) continue
    const tokens = name.split(/\s+/)
    for (const token of tokens) {
      if (token.length === 0) continue
      seedToken(token)
    }
  }

  return results
}

// ─── applyCorrections ───────────────────────────────────────────────────────

function escapeRegExp(input: string): string {
  return input.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/**
 * Rewrites `transcript` using `corrections`. Pure, case-preserving,
 * word-boundary-safe (uses Unicode letter/number boundaries, so it will not
 * corrupt a real word that merely contains a correction's `heard` text as a
 * substring, and correctly isolates possessives like "Mira's"). All matches
 * are located against the *original* text in a single pass, so corrections
 * never chain into one another.
 */
export function applyCorrections(
  transcript: string,
  corrections: NameCorrection[]
): { text: string; applied: Array<{ heard: string; correct: string; count: number }> } {
  if (transcript.length === 0 || corrections.length === 0) {
    return { text: transcript, applied: [] }
  }

  // Dedupe by heard (case-insensitive, first wins) and drop degenerate
  // entries — including heard === correct, which would otherwise be a
  // no-op correction that (if ever reapplied) could loop forever.
  const byHeard = new Map<string, NameCorrection>()
  for (const correction of corrections) {
    const heard = correction.heard.trim()
    const correct = correction.correct.trim()
    if (heard.length === 0 || correct.length === 0) continue
    if (heard.toLowerCase() === correct.toLowerCase()) continue
    const key = heard.toLowerCase()
    if (!byHeard.has(key)) byHeard.set(key, { ...correction, heard, correct })
  }

  const list = Array.from(byHeard.values()).sort((a, b) => b.heard.length - a.heard.length)
  if (list.length === 0) {
    return { text: transcript, applied: [] }
  }

  const pattern = list.map((c) => escapeRegExp(c.heard)).join('|')
  const boundaryRe = new RegExp(
    '(?<![' + WORD_RANGE + '])(' + pattern + ')(?![' + WORD_RANGE + '])',
    'gi'
  )

  const counts = new Map<string, number>()
  const text = transcript.replace(boundaryRe, (match) => {
    const key = match.toLowerCase()
    const correction = byHeard.get(key)
    if (!correction) return match // defensive; should be unreachable
    counts.set(key, (counts.get(key) ?? 0) + 1)
    return matchCase(match, correction.correct)
  })

  const applied = list
    .filter((c) => counts.has(c.heard.toLowerCase()))
    .map((c) => ({
      heard: c.heard,
      correct: c.correct,
      count: counts.get(c.heard.toLowerCase()) as number,
    }))

  return { text, applied }
}

// ─── learnCorrection ────────────────────────────────────────────────────────

const LEADING_TRAILING_NON_LETTER_RE = new RegExp(
  '^[^' + LETTER_RANGE + ']+|[^' + LETTER_RANGE + ']+$',
  'g'
)
const TRAILING_NON_LETTER_RE = new RegExp('[^' + LETTER_RANGE + ']+$', 'g')
const POSSESSIVE_RE = /['’]s$/i

/** Strips leading/trailing punctuation and a trailing possessive ('s / 's). */
function toBareWord(word: string): string {
  let bare = word.replace(LEADING_TRAILING_NON_LETTER_RE, '')
  bare = bare.replace(POSSESSIVE_RE, '')
  bare = bare.replace(TRAILING_NON_LETTER_RE, '')
  return bare
}

/**
 * Diffs a parent's manual edit of one entry (`before` -> `after`) and detects
 * whether the edit was a name fix, so it can be corrected silently forever
 * after (PRD §17.3, edit-as-signal — surfaced to nobody, applied every time).
 *
 * Conservative by design: only recognizes a single-word substitution (found
 * via common-prefix / common-suffix trimming, so it is robust to the
 * surrounding sentence being identical on both sides) where the corrected
 * word exactly matches one of the caller's `known` names and the original
 * word is phonetically plausible as a mishearing of it. Anything else —
 * insertions, deletions, multi-word rewrites, edits that don't land on a
 * known name — returns null rather than guessing.
 */
export function learnCorrection(
  before: string,
  after: string,
  known: string[]
): NameCorrection | null {
  if (before === after) return null

  const beforeWords = before.split(/\s+/).filter((w) => w.length > 0)
  const afterWords = after.split(/\s+/).filter((w) => w.length > 0)
  if (beforeWords.length === 0 || afterWords.length === 0) return null

  let prefix = 0
  while (
    prefix < beforeWords.length &&
    prefix < afterWords.length &&
    beforeWords[prefix] === afterWords[prefix]
  ) {
    prefix++
  }

  let suffix = 0
  const maxSuffix = Math.min(beforeWords.length - prefix, afterWords.length - prefix)
  while (
    suffix < maxSuffix &&
    beforeWords[beforeWords.length - 1 - suffix] === afterWords[afterWords.length - 1 - suffix]
  ) {
    suffix++
  }

  const beforeMid = beforeWords.slice(prefix, beforeWords.length - suffix)
  const afterMid = afterWords.slice(prefix, afterWords.length - suffix)

  // Only trust an unambiguous single-word-for-single-word substitution.
  if (beforeMid.length !== 1 || afterMid.length !== 1) return null

  const beforeClean = toBareWord(beforeMid[0])
  const afterClean = toBareWord(afterMid[0])
  if (beforeClean.length === 0 || afterClean.length === 0) return null
  if (beforeClean.toLowerCase() === afterClean.toLowerCase()) return null

  const matchedKnown = known.find((name) => name.toLowerCase() === afterClean.toLowerCase())
  if (!matchedKnown) return null

  // Require the "heard" word to be phonetically plausible as a mishearing of
  // the known name — otherwise this is an unrelated content edit that
  // happens to land on a name, not a transcription fix.
  if (soundex(beforeClean) !== soundex(matchedKnown)) return null

  return {
    heard: beforeClean,
    correct: matchedKnown,
    hit_count: 1,
    source: 'learned',
  }
}
