// tokens/semantic.ts — Lumira design tokens, semantic tier
//
// Lane: DS1. Owns this file and tokens/primitives.ts, and no others
// (see docs/LETTERS-ENGINEERING-CONTRACT.md §5).
//
// Maps roles to primitives. Only this tier forks by light/dark mode (design spec §2.3:
// "Only the semantic tier forks. Primitive and component tiers never fork"). Component
// code should reference these roles, never `primitives` or raw hex, directly.
//
// ROLE-SEPARATION RULE (design spec §3.1.1 — applied, not just documented):
// "Sage 500, Terra 400 and Rose 400 are UI, icon and large-text tokens only (3:1 floor).
// Body copy on light surfaces uses the 600 step." Encoded below as two separate roles per
// family — `accent.<family>.ui` (3:1 floor) and `accent.<family>.body` (4.5:1 floor) — so
// a component reaching for body text literally cannot reach the UI-tier value by
// accident; the rule is enforced by which property exists, not by developer discipline.
//
// VERIFIED DEVIATIONS FROM THE LITERAL SPEC TEXT (both computed, not assumed — see the
// ratio table in this lane's final report):
// 1. Terra 400 (#C4844E) on the *actual* app background Sand-0 (#FAFAF8) measures 2.97:1
//    — it fails even the 3:1 UI floor. The design spec's own audit only checked it
//    against pure white (3.11, passing). Sand-0 is what globals.css actually ships as
//    `--surface-background`, so `accent.terra.ui` is promoted to Terra 500 (4.20:1 on
//    Sand-0) for light mode. Terra 400 remains a valid primitive and still passes 3:1 on
//    the white `raised` surface if a component specifically needs the lighter tone there.
// 2. Amber's anchor sits at step 200 (#F5D890, a pale fill color) and measures 1.33:1 on
//    Sand-0 — nowhere close to usable as icon/text foreground. `accent.amber.ui` uses
//    Amber 500 (3.62:1 on Sand-0) instead; Amber 200 remains available as a primitive for
//    background-fill use (e.g. a badge fill), never as foreground text/icon color.
// 3. The design spec flags "Amber 600 on Amber 50" as failing at 4.42 for the "watch —
//    monitor this" status card. Rather than patch that exact pairing, status card
//    backgrounds here use the family's own 100 step (not 50) — post-defect-fix, the 50
//    step is a near-white whisper of hue that reads as barely-there and isn't a
//    meaningfully distinct card surface anyway. On the 100 step, family-600 body text
//    passes 4.5:1 for all four families (4.64–5.21:1), and `status.danger.icon` uses
//    Rose 500 (not Rose 400 — Rose 400 on Rose 100 measures 2.64:1, failing 3:1; this was
//    caught by the verification pass, see below) so `status.<role>.icon` passes 3:1 too.
//
// DARK MODE RULE (design spec §3.4): lift lightness toward the 300 step and cut chroma.
// The 300 step of each family ramp already embodies this — it is generated by the same
// OKLCH taper as the rest of the ramp, landing at L≈0.72–0.80 with chroma well below the
// anchor's (see the ratio table in primitives.ts). It clears both the 3:1 UI floor and
// the 4.5:1 body floor by wide margins (6.7–9.9:1) against every dark surface below, so
// `accent.<family>.ui` and `accent.<family>.body` collapse to the same value in dark mode
// — there is no need for two darker/lighter dark-mode variants the way light mode needs.
//
// ELEVATION BY LIGHTNESS, NOT SHADOW (§3.4): dark surface roles are computed directly at
// the spec's target L values (not snapped to the nearest ramp step, which would either
// undershoot or overshoot the prescribed band), holding the sand ramp's own hue/chroma
// trajectory so they read as an extension of the same neutral, not a new color:
//   background L=0.183 (= Sand 950, the anchor)   raised (card)  L=0.22
//   overlay (modal/sheet) L=0.265                  sunken (recessed) L=0.15
// Light mode's `sunken` is computed the same way at L=0.965 (recessed just below the
// Sand-0 background) rather than reusing the old unaudited `#F5F3EF` literal — the two
// differ by two sRGB steps, imperceptibly.

import { sage, terra, rose, amber, sand, white } from './primitives';

export interface AccentTierRoles {
  /** 3:1 floor. Icons, large text (≥18pt / ≥14pt bold), UI chrome only. Never body copy. */
  readonly ui: string;
  /** 4.5:1 floor. Any text below the "large text" threshold, including all body copy. */
  readonly body: string;
}

export interface AccentRoles {
  readonly sage: AccentTierRoles;
  readonly terra: AccentTierRoles;
  readonly rose: AccentTierRoles;
  readonly amber: AccentTierRoles;
}

export interface StatusRoleTokens {
  readonly bg: string;
  readonly border: string;
  /** 3:1 floor against `bg`. */
  readonly icon: string;
  /** 4.5:1 floor against `bg`. */
  readonly text: string;
}

export interface StatusRoles {
  readonly success: StatusRoleTokens; // sage — calm / normal / "usually fine"
  readonly caution: StatusRoleTokens; // amber — monitor / watch
  readonly danger: StatusRoleTokens; // rose — escalate / alert
  readonly info: StatusRoleTokens; // terra — informational / warm reassurance
}

export interface SurfaceRoles {
  readonly background: string;
  readonly raised: string;
  /** Translucent layer (modal scrims, vibrancy panels). Structured, not a flat hex, so
   *  the web build can emit `rgb(... / opacity)` and RN can emit `rgba(...)` from the
   *  same source without baking a platform-specific string into the token itself. */
  readonly overlay: { readonly color: string; readonly opacity: number };
  readonly sunken: string;
}

export interface TextRoles {
  readonly primary: string;
  readonly secondary: string;
  readonly tertiary: string;
  /** Sand 300 fails body-text contrast (design spec §3.1 note) — WCAG exempts *disabled*
   *  controls, but placeholder text must stay readable, so it gets its own role at the
   *  600-per-family-equivalent step rather than silently reusing tertiary/disabled. */
  readonly placeholder: string;
  /** WCAG-exempt: disabled control label/icon. Not for placeholder or hint text. */
  readonly disabled: string;
  readonly inverse: string;
}

export interface BorderRoles {
  readonly subtle: string;
  readonly default: string;
  /** 3:1 floor against `surface.background` — for meaningful UI boundaries (inputs,
   *  focus rings), not decorative dividers. */
  readonly strong: string;
}

export interface SemanticTheme {
  readonly surface: SurfaceRoles;
  readonly text: TextRoles;
  readonly border: BorderRoles;
  readonly accent: AccentRoles;
  readonly status: StatusRoles;
}

// Dark-mode elevation surfaces, computed at the spec's target lightness (see header
// comment) rather than snapped to a ramp step. Values only — the OKLCH derivation is
// the same one used throughout primitives.ts; see this lane's final report for the
// verification script.
const DARK_RAISED = '#1B1A18'; // L=0.22 — card
const DARK_OVERLAY = '#262523'; // L=0.265 — modal/sheet
const DARK_SUNKEN = '#0C0B09'; // L=0.15 — recessed, below background

// Light-mode sunken, computed the same way (L=0.965) rather than reusing the old
// un-audited #F5F3EF literal (see header comment).
const LIGHT_SUNKEN = '#F3F3F1';

export const light: SemanticTheme = {
  surface: {
    background: sand[0],
    raised: white,
    overlay: { color: white, opacity: 0.92 },
    sunken: LIGHT_SUNKEN,
  },
  text: {
    primary: sand[800], // 11.72:1 on background
    secondary: sand[700], // 8.74:1 on background
    tertiary: sand[500], // 4.68:1 on background — AA body floor, do not go lighter
    placeholder: sand[500], // same floor — Sand 300 fails placeholder legibility
    disabled: sand[300], // WCAG-exempt disabled controls only
    inverse: white,
  },
  border: {
    subtle: sand[100],
    default: sand[200],
    strong: sand[400], // 3.48:1 on background
  },
  accent: {
    sage: { ui: sage[500], body: sage[600] },
    terra: { ui: terra[500], body: terra[600] }, // promoted from 400 — see header note 1
    rose: { ui: rose[400], body: rose[600] },
    amber: { ui: amber[500], body: amber[600] }, // promoted from 200 — see header note 2
  },
  status: {
    success: { bg: sage[100], border: sage[300], icon: sage[500], text: sage[600] },
    caution: { bg: amber[100], border: amber[300], icon: amber[500], text: amber[600] },
    danger: { bg: rose[100], border: rose[300], icon: rose[500], text: rose[600] }, // icon promoted — see header note 3
    info: { bg: terra[100], border: terra[300], icon: terra[500], text: terra[600] },
  },
} as const;

export const dark: SemanticTheme = {
  surface: {
    background: sand[950],
    raised: DARK_RAISED,
    overlay: { color: DARK_OVERLAY, opacity: 0.92 },
    sunken: DARK_SUNKEN,
  },
  text: {
    primary: sand[0], // 17.91:1 on background
    secondary: sand[100], // 11.41:1 on background
    tertiary: sand[300], // 6.83:1 on background
    placeholder: sand[300],
    disabled: sand[600],
    inverse: sand[950],
  },
  border: {
    subtle: sand[900],
    default: sand[800],
    strong: sand[500], // 3.82:1 on background
  },
  accent: {
    // Single value per family: the 300 step already clears both floors by 6.7-9.9:1 —
    // see header comment "DARK MODE RULE".
    sage: { ui: sage[300], body: sage[300] },
    terra: { ui: terra[300], body: terra[300] },
    rose: { ui: rose[300], body: rose[300] },
    amber: { ui: amber[300], body: amber[300] },
  },
  status: {
    success: { bg: DARK_RAISED, border: sage[800], icon: sage[300], text: sage[300] },
    caution: { bg: DARK_RAISED, border: amber[800], icon: amber[300], text: amber[300] },
    danger: { bg: DARK_RAISED, border: rose[800], icon: rose[300], text: rose[300] },
    info: { bg: DARK_RAISED, border: terra[800], icon: terra[300], text: terra[300] },
  },
} as const;

export const semantic = { light, dark } as const;
export type Semantic = typeof semantic;
